### PR TITLE
Fix contact form

### LINKED ISSUE #267: Fix Contact form
Our contact form seems to do nothing.

https://die-lernwerkstatt.org/contact

https://github.com/Lernwerkstatt/site/blob/master/src/views/contact.hbs

### PR DESCRIPTION
**Pull request by danielstreif**
**What**:
- use nodemailer to send messages from contact form
- add basic verification step

Fixes #267

### CODE REVIEW

**Comment by danielstreif** [comment]
@pheeria @jarjan This is just an attempt so far. I did not add any success or failure messages yet, so the ux side is not that great. Anyway, the messages would actually be send 😉 

@jarjan is right though, the emails might end up as spam.

**Comment by pheeria** [comment]
Sorry for being late. 🙁 
I'll check out the code locally, and if it works, I'll try to include env variables to prod and deploy.

File: src/routes/contact.js [hunk 1]
```diff
@@ -1,10 +1,46 @@
...
+const bodyParser = require("body-parser");
 const policy = require("../../data/policy.json");
 
+const app = express();
 const router = express.Router();
 
-router.get("/contact", (req, res) => {
-  res.render("contact", policy);
-});
+app.use(bodyParser.urlencoded({ extended: true }));
```
Comment (pheeria) [inline src/routes/contact.js:9]: Maybe we can do it in `src/index.js`?
This here looks like a hack 🙂

File: src/views/contact.hbs [hunk 2]
```diff
@@ -30,24 +30,29 @@
...
       <div class="form-group">
-        <textarea type="text" class="form-control form-control-sm" id="message" rows="10"
+        <textarea type="text" class="form-control form-control-sm" id="message" name="message" rows="10"
           placeholder="{{{__ "common_letter"}}}" aria-label="{{{__ "common_letter"}}}" required></textarea>
       </div>
+      <div class="form-group">
+        <label class="control-label" for="verification">{{{__ "contact_verify"}}}</label>
+        <input type="text" class="form-control form-control-sm" id="verification" name="verification"
+          placeholder="{{{__ "contact_verification"}}}">
+      </div>
```
Comment (pheeria) [inline src/views/contact.hbs:55]: Why do we need to verify?

File: src/routes/contact.js (hunk 1 above)
Comment (danielstreif) [reply src/routes/contact.js:9]: Just realized we already called it in `src/index.js`. Will remove it 🙂

File: src/views/contact.hbs (hunk 2 above)
Comment (danielstreif) [reply src/views/contact.hbs:55]: I just saw it in an example and thought it doesn't hurt to prevent spam. You are right though, it might confuse some people and I guess the chance for someone setting up a bot to spam Lernwerkstatt is rather low 😄 Let me know if I should remove it.
